spring.datasource.url=jdbc:mysql://localhost:3306/business_db
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

jwt.token= 9f8c2b7a6e4d1a0f3c9e8b7d6a5f4c3b2e1d0f9a8b7c6d5e4f3a2b1c0d9e8f7
jwt.expiry=3600000